# Generated by Django 4.1.2 on 2022-10-19 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'hermaphrodite')])),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auths.user')),
            ],
            bases=('auths.user',),
        ),
    ]
