# Generated by Django 4.1.2 on 2022-10-27 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_user_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
